### ISSUE TITLE
AttributeError: 'Request' object has no attribute '_enc_params' 

### ISSUE THREAD

**Issue by amalakar** [maraujop/requests-oauth#34]
Hi, 

I use the request-oauth library in a netflix webservice client library that I have written (pyflix2). One of the users in Windows has found that the oauth hook is throwing the following error:

```
Traceback (most recent call last):
  File "C:\Users\guthrie\AppData\Roaming\Python\Python27\site-packages\requests\hooks.py", line 47, in dispatch_hook
    hook_data = hook(hook_data) or hook_data
  File "C:\Users\guthrie\AppData\Roaming\Python\Python27\site-packages\oauth_hook\hook.py", line 207, in __call__
    if request._enc_params:
AttributeError: 'Request' object has no attribute '_enc_params'
```

I don't have windows environment to reproduce the bug, hoping that the error message would give you some pointer. 

Original comment: https://github.com/amalakar/pyflix2/issues/5#issuecomment-6892067

Thanks,
Arup

**Comment by maraujop** [comment]
Hi Arup,

Most likely the problem is that he is using a new version of requests with an old version of requests-oauth. This bug here is already solved long time ago. There is probably a versions mismatch in Windows.

Cheers,
Miguel

**Comment by grguthrie** [comment]
Thanks,
I have requests-0.13.2 & requests_oauth-0.4.1 (both from activeState python).

requests-0.13.2-py2.7.egg-info
requests_oauth-0.4.1-py2.7.egg-info
