### ISSUE TITLE
Can't import modules correctly

### ISSUE THREAD

**Issue by lostVkng** [maraujop/requests-oauth#41]
There is something inncorrect with the importing of modules,

```
python3.2
from oauth_hook import OAuthHook
```

leads to

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/requests_oauth-0.4.1-py3.2.egg/oauth_hook/__init__.py", line 1, in <module>
    from hook import OAuthHook
ImportError: No module named hook
```

I tried moving the hook code to the **init**.py but then the same error comes up with auth.py and just creates more issues.

Also note: I tried it in python3.3 and same issue

```
    from oauth_hook import OAuthHook
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/oauth_hook/__init__.py", line 1, in <module>
    from hook import OAuthHook
ImportError: No module named 'hook'
```

**Comment by yash-chowdhary** [comment]
I also faced this issue. Is there a solution?

**Comment by sana-farooqui** [comment]
It only works with Python2
